services:
  minio:
    image: minio/minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
  minio_init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./minio_init:/data
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9000 admin admin123 &&
      mc mb minio/data &&
      mc anonymous set public minio/data &&
      mc cp --recursive /data/* minio/data/ &&
      echo 'Minio initialized'
      "
  postgres:
    image: postgres:14.1
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
  minio_init:
    driver: local

