name: Airflow DAG Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install apache-airflow
        pip install apache-airflow-providers-amazon
        pip install apache-airflow-providers-postgres
        pip install boto3
        pip install psycopg2-binary
        pip install pylint
        
    - name: Set Airflow home
      run: |
        export AIRFLOW_HOME=$(pwd)/airflow
        
    - name: Run pylint
      run: |
        pylint airflow/dags/
        
    - name: Run tests with coverage
      run: |
        python -m pytest tests/ -v --cov=. --cov-report=xml
        
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
